# XC-RECON System Configuration

app:
  name: "XC-RECON-SYSTEM"
  version: "2.0.0"
  debug: true
  log_level: "INFO"
  host: "0.0.0.0"
  port: 8000

# 数据库配置
database:
  type: "sqlite"  # 开发环境使用sqlite，生产环境改为postgresql
  url: "sqlite:///./xc_recon.db"
  # 生产环境配置：
  # host: "localhost"
  # port: 5432
  # name: "xc_recon"
  # user: "postgres"
  # password: "password"
  pool_size: 10
  echo: false  # 设为true可以看到SQL语句

# Redis 配置（可选）
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""
  enabled: false  # 开发环境暂时禁用

# API 配置
api:
  cors_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"

# 安全配置
security:
  secret_key: "your-secret-key-here-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 30

# 设备配置
devices:
  fr3_right_arm:
    ip: "192.168.58.2"
    port: 20003
    timeout: 5
    enabled: true
  
  fr3_left_arm:
    ip: "192.168.58.3"
    port: 20003
    timeout: 5
    enabled: true
  
  hermes_chassis:
    ip: "192.168.31.211"
    port: 1448
    timeout: 10
    enabled: true

# AI 配置
ai:
  openai:
    api_key: "${OPENAI_API_KEY}"  # 从环境变量读取
    model: "gpt-4"
    max_tokens: 2000
    temperature: 0.7
    enabled: false  # 开发环境暂时禁用
  
  local_models:
    enabled: false
    model_path: "./models"
    device: "cpu"  # cpu/cuda

# 文件存储配置
storage:
  type: "local"  # local/minio/s3
  upload_path: "./data/uploads"
  max_file_size: "100MB"
  allowed_extensions: [".stl", ".stp", ".step", ".obj", ".ply"]

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/app.log"
  max_size: "10MB"
  backup_count: 5